### ISSUE TITLE
Handle edge case where the same `Subsignal` uses multiple `Connectors`

### ISSUE THREAD

**Issue by cr1901** [m-labs/nmigen-boards#18]
Occasionally, it is possible a user will want to add their custom `Resource` to their boards `Connector`s that matches the following conditions:

* A `Subsignal` of their shiny new `Resource` has multiple `Pins` that should be associated with it.
* The `Pins` of this `Subsignal` will be spread out across multiple `Connector`s.

`omigen` already handles this case by hardcoding the connector to use into the `Pins` string, as per [this example](https://github.com/m-labs/migen/blob/master/migen/build/platforms/mercury.py#L142-L155) on the `b` `Subsignal`.

What should the equivalent `nmigen` behavior be?

## My Proposal
```
vga = [
        ("vga_out", 0,
            Subsignal("hsync", PinsN("3", dir="o", conn=("led", 0))),
            Subsignal("vsync", PinsN("4", dir="o", conn=("led", 0))),

            Subsignal("r", Pins("1 2 3", dir="o", conn=("dio", 0))),
            Subsignal("g", Pins("4 5 6", dir="o", conn=("dio", 0))),
            Subsignal("b", Pins("7", dir="o", conn=("dio", 0)),
                           Pins("1", dir="o", conn=("clkio", 0))),
            Attrs(IOSTANDARD="LVCMOS33", SLEW="FAST")
        )
    ]
```

**Comment by whitequark** [comment]
That's already handled by doing something like:
```
vga = [
        ("vga_out", 0,
            Subsignal("hsync", PinsN("led_0:3", dir="o")),
            Subsignal("vsync", PinsN("led_0:4", dir="o")),

            Subsignal("r", Pins("dio_0:1 dio_0:2 dio_0:3", dir="o")),
            Subsignal("g", Pins("dio_0:4 dio_0:5 dio_0:6", dir="o")),
            Subsignal("b", Pins("dio_0:7 clkio_0:1", dir="o")),
            Attrs(IOSTANDARD="LVCMOS33", SLEW="FAST")
        )
    ]
```
